version: "3"

services:
  minecraft:
    volumes:
      - data_minecraft:/data
    image: belooussov/minecraft:1.12.2
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "3"
          memory: 8G 
      restart_policy:
        condition: on-failure
    restart: always
    ports:
      - "25565:25565"
    environment:
      - MINECRAFT_VERSION=1.12.2

volumes:
        data_minecraft:
            driver: "local"
